### ISSUE TITLE
Description and Categories of MsTest are not reported

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/agent-net-vstest#12]
```csharp
[TestMethod]
        [Description("This is description of TestMethod1")]
        [TestCategory("Category1"), TestCategory("Category2")]
        public void TestMethod1()
```

![screenshot_1](https://user-images.githubusercontent.com/22616990/49648525-2e326500-fa37-11e8-88f9-b468742e4601.png)

**Comment by nvborisenko** [comment]
Issue is in testfx repo: https://github.com/Microsoft/testfx/issues/529

**Comment by nvborisenko** [comment]
Categories moved to properties. Need investigate where in ObjectModel we can find them, and don't forget about others test adapters.

**Comment by suszi88** [comment]
I started working with ReportPortal and initially I was able to see Description but when I updated MSTest.Framework and Adapter to latest version 2.0.0 I cannot see them anymore. Can it be connected to this bug?

**Comment by nvborisenko** [comment]
Absolutely. It is easy fix, I will try to resolve it. Please ping me again if it will not be resolved during acceptable range of time.

**Comment by nvborisenko** [comment]
I am able to resolve issue with `Categories` for MsTest. But I would also consider others adapters/frameworks. The behavior is different for them, even for MsTest v1.4 and v2.0. To resolve it partially we want to collect information about how Visual Studio Test provide information about test results, and try to consider all ways.

I propose to release a new version of beta-package. You, as tester, will just introduce new property in config file, and you will be able to see all related information about test result in ReportPortal (as separate log message with attachment).

Just share it with us, including UnitTestFramework/TestAdapter version.

@suszi88 will you be able to help to collect this kind of information.

PS: I don't see test `Description` in results, need deeper investigation.

**Comment by suszi88** [comment]
![NuGetPackages](https://user-images.githubusercontent.com/54896782/64326154-5ac4de80-cfc1-11e9-9938-6eef06a1319c.PNG)
Those are NuGet packages with versions which I'm using in project

**Comment by suszi88** [comment]
[TestMethod]
        [Description("Checking if test is alive")]
        public void Alive()
        {
            Assert.IsTrue(true);
        }

**Comment by suszi88** [comment]
Although I'm not sure if I will be able to test potential fix as I'm not in control of ReportPortal instance which is currently in version: Build: 4.3.6

**Comment by suszi88** [comment]
Thanks Nikolay, working now
![ReportPortalDescription](https://user-images.githubusercontent.com/54896782/64419392-bc09b200-d094-11e9-9848-1aa408cd0276.PNG)
