### ISSUE TITLE
Support test suites

### ISSUE THREAD

**Issue by yurii-hunter** [reportportal/agent-net-vstest#15]
I would like to see tests grouped by suite (class name) instead of all located in one Default suite.
We can use fully qualified name for extracting class name.

**Comment by nvborisenko** [comment]
Implemented in version 2.0.0-beta.3. This is in beta still because all suites are in progress status until launch finishes.

**Comment by yurii-hunter** [comment]
Looks like it is the only way how it could be implemented I will try this beta.
Thanks!
