### ISSUE TITLE
Setting environment variable for ReportPortal_Launch_IsDebugMode not consistent

### ISSUE THREAD

**Issue by muttonchop** [reportportal/agent-net-vstest#19]
With `2.0.0-beta4` setting the environment variable `ReportPortal_Launch_IsDebugMode` as detailed in the documentation does not correctly set the Debug flag. 

Using `ReportPortal_Launch_DebugMode` correctly sets the flag and reports the test result.

**Comment by nvborisenko** [comment]
Thanks for catching it. Updated doc in 2.0 branch.

**Comment by muttonchop** [comment]
thanks!
