### ISSUE TITLE
Test results not going to RP from Test Explorer

### ISSUE THREAD

**Issue by staind825** [reportportal/agent-net-vstest#23]
I was able to get my tests to write to report portal when executing through the command line. However, when running directly through the test explorer, the results are not sent to RP. I am getting this same behavior on Xunit and VStest. However, i have an nunit project that works when running from test explorer.

**Comment by nvborisenko** [comment]
@staind825 please refer https://github.com/reportportal/agent-net-vstest#visual-studio-test-explorer doc, added recently.
You can play with [example](https://github.com/reportportal/example-net-vstest)

Let's us know whether it works for you.

**Comment by staind825** [comment]
thank you @nvborisenko ! i think we are good here now.

**Comment by BilalKhan199** [comment]
> @staind825 please refer https://github.com/reportportal/agent-net-vstest#visual-studio-test-explorer doc, added recently.
> You can play with [example](https://github.com/reportportal/example-net-vstest)
> 
> Let's us know whether it works for you.

It does not work, tests running from test explorer does not log results in RP.

**Comment by nvborisenko** [comment]
Because of new version of Visual Studio :(

**Comment by BilalKhan199** [comment]
> Because of new version of Visual Studio :(

I noticed, I tried on vs 2017 and 2019 does not work. I'm now test it with Azure Devops pipline, i'm not sure if its going to work or not? thanks

**Comment by nvborisenko** [comment]
We support primary usage of tests execution, via console:
- `dotnet test`
- `dotnet vstest`
- `vstest.console.exe`

In additional, we are trying to support VS Test Explorer.

**Comment by BilalKhan199** [comment]
@nvborisenko  have a look at this issue, https://github.com/microsoft/azure-pipelines-tasks/issues/12451

specially this comment

>  Just a side comment for anyone else looking at this in future, I learnt it hard way by scanning thru every line of the logs that the custom logger dll needs to end with the words "testlogger" for it to be recognized, even if its specified in testadapterpath etc. It blows my mind, but it is what it is.

**Comment by nvborisenko** [comment]
Thanks @BilalKhan199  this is how I am doing.

Also please track related issue: https://github.com/reportportal/agent-net-vstest/issues/27#issuecomment-594468846

**Comment by nvborisenko** [comment]
@BilalKhan199 do you have issues in Azure DevOps with RP test logger?

**Comment by BilalKhan199** [comment]
> @BilalKhan199 do you have issues in Azure DevOps with RP test logger?

Sorry for late reply, i was only able run test in Azure DevOps by setting Parallelism to None. But that was not solution i was looking for, i need Parallelism as i have more than 10 test agents.
![image](https://user-images.githubusercontent.com/29634913/83071997-ff99b700-a03b-11ea-8bd1-01316e84417d.png)

**Comment by nvborisenko** [comment]
Hi @BilalKhan199 , seems you have another issue in ADO. Please crerate separate issue to discuss it, with details how you configured the rp integration.

**Comment by BilalKhan199** [comment]
> Hi @BilalKhan199 , seems you have another issue in ADO. Please crerate separate issue to discuss it, with details how you configured the rp integration.

I noticed the run settings are working now, so I will try the parallelism again, i think it should work now, i will let you know.
