### ISSUE TITLE
Failed tests with NUnit Assert.Multiple are displayed as different tests

### ISSUE THREAD

**Issue by olegbaslak** [reportportal/agent-net-vstest#25]
If test has several failed asserts in Assert.Multiple, failed asserts are displayed as different tests in Report Portal

![image](https://user-images.githubusercontent.com/1713494/59692539-d9458780-91ed-11e9-9af5-01df4acbe79c.png)

**Comment by nvborisenko** [comment]
Reported issue to NUnit3TestAdapter https://github.com/nunit/nunit3-vs-adapter/issues/630

**Comment by nvborisenko** [comment]
Fixed in NUnit3TestAdapter v3.14.
