### ISSUE TITLE
Run Test from powershell using vstest.console.exe "Could not find a test logger with AssemblyQualifiedName,URI or FriendlyName "ReportPortal"

### ISSUE THREAD

**Issue by EricNolan91** [reportportal/agent-net-vstest#26]
When I run my specflow test from the powershell command line I get an error with the logger saying Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'ReportPortal'.

I am using the most version v3.0.213 of SpecFlow and the  most recent versions of ReportPortal.VSTest.TestLogger(v2.0.7) and ReportPortal.Shared(v2.2.1) however it will still not pick up on the ReportPortal logger. All dlls are present in the running directory. I am using .net framework 4.7.1. would this cause an issue with the logger or is it something else?

**Comment by nvborisenko** [comment]
To investigate issue please execute vstest with `/Diag:log.txt` parameter. And please share it here. I guess you forgot to copy `reportportal.config.json` file to output folder.

Also you might be interested in https://github.com/reportportal/agent-net-specflow. Just try and compare how reports are look.

**Comment by EricNolan91** [comment]
[log.txt](https://github.com/reportportal/agent-net-vstest/files/3349320/log.txt)

The `reportportal.config.json` file is present in the output directory and it has all of the information needed to report.

**Comment by nvborisenko** [comment]
`TestLoggerManager: Error while initializing logger: logger://ReportPortal, Exception details: System.Collections.Generic.KeyNotFoundException: Property 'Server:Url' not found in the configuration.`
Please share content of `reportportal.config.json` file, will see whether the format is correct. And please double check that this file is located near with dll.

**Comment by nvborisenko** [comment]
Later in your log I see `TestLoggerManager: Error while initializing logger: logger://ReportPortal, Exception details: System.ArgumentException: Only 'http' and 'https' schemes are allowed.`. Check property `Server_Url`. Example of correct url is `https://rp.epam.com/api/v1/`

**Comment by EricNolan91** [comment]
![image](https://user-images.githubusercontent.com/52422818/60505698-26c8f680-9cbc-11e9-9c9c-ccc83d7f4e4f.png)
All files are present

`{
  "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-specflow/f9d8b092cb9147d38539c25c3e59c07b4dc82938/src/ReportPortal.SpecFlowPlugin/ReportPortal.config.schema",
  "enabled": true,
  "server": {
    "url": "ie-qe-876yfujuy9928:8080/api/v1/",
    "project": "superadmin_personal",
    "authentication": {
      "uuid": "c4244a85-60c2-4d53-aec5-83d89156d65c"
    }
  },
  "launch": {
    "name": "Test",
    "description": "This is the Test launch",
    "debugMode": false,
    "tags": [ "t1", "t2" ]
  }
}`

**Comment by nvborisenko** [comment]
Add `http://` at the beginning of `url` property.

**Comment by EricNolan91** [comment]
Adding `http://` worked. thank you
