### ISSUE TITLE
Logger gets unhanded exception while extricating fullPath from the full test name (fullName)

### ISSUE THREAD

**Issue by yurii-hunter** [reportportal/agent-net-vstest#28]
https://github.com/reportportal/agent-net-vstest/blob/a6d01fae68f5c7e231fce21782a58a26e5a78fbc/src/ReportPortal.VSTest.TestLogger/ReportPortalLogger.cs#L124

In case user uses xUnit.net the ```e.Result.TestCase.DisplayName``` is equal to ```e.Result.TestCase.FullyQualifiedName```. 
It causes exception on line number [129](https://github.com/reportportal/agent-net-vstest/blob/a6d01fae68f5c7e231fce21782a58a26e5a78fbc/src/ReportPortal.VSTest.TestLogger/ReportPortalLogger.cs#L129) because logger tries to get substring with length -1 
```csharp
var fullPath = fullName.Substring(0, fullName.Length - testName.Length - 1);
```
it will became
```csharp
var fullPath = fullName.Substring(0, - 1);
```

Looks like the fastest solution is to try to get test name from the DisplayName, but i'm not sure about this.
```csharp
var fullName = e.Result.TestCase.FullyQualifiedName;
var displayName = e.Result.TestCase.DisplayName ?? fullName;
var testName = displayName.Split('.').Last();

var fullPath = fullName.Substring(0, fullName.Length - testName.Length - 1);
```

**Comment by nvborisenko** [comment]
@yurii-hunter could you please share a piece of code how your test looks like which causes this issue?

**Comment by yurii-hunter** [comment]
Microsoft.NET.Test.Sdk Version=16.2.0 
xunit Version = 2.4.1
xunit.runner.visualstudio Version = 2.4.1
Project Type - Class Library (.net core)

```csharp
[Fact]
public void TestMethod()
{
    Assert.True(false);
}
```
@nvborisenko  vstest logger creates test launch bat can not report any test there

**Comment by nvborisenko** [comment]
Thanks, will take a look in 1 week when get back to PC.

**Comment by yurii-hunter** [comment]
![jfPrCm1icB](https://user-images.githubusercontent.com/3284574/61775445-9fc1f680-ae01-11e9-94af-c4dc4ac9c336.gif)

A little bit more details:
if DisplayName is not specfified - then `FullyQualifiedName` equals `DisplayName`
if DisplayName is specified `[Fact(DisplayName = "Test.Method")]` - then `DisplayName` shows specified display name `"Test.Method"`

**Comment by nvborisenko** [comment]
Right, got the same results. This behavior is specific only foe xunit tests. Not sure whether this should be resolved on our side or xunit adapter side.

Some variants:
```
fq: ExampleUnitTests.XUnitTests.UnitTest3.Test4, dn: ExampleUnitTests.XUnitTests.UnitTest3.Test4(a: "1.postfix")
fq: ExampleUnitTests.XUnitTests.UnitTest3.Test4, dn: ExampleUnitTests.XUnitTests.UnitTest3.Test4(a: "2.postfix")
fq: ExampleUnitTests.XUnitTests.UnitTest3.Test3, dn: Dot.Test3
fq: ExampleUnitTests.XUnitTests.UnitTest3.Test2, dn: OverriddenTest2
fq: ExampleUnitTests.XUnitTests.UnitTest3.Test1, dn: ExampleUnitTests.XUnitTests.UnitTest3.Test1
```
where `fq` is fully qualified name, `dn` - Display Name.

I don't see how to understand what is namespace and name of test based on this information :(.

We don't meet this behavior in mstest and nunit adapters.

**Comment by yurii-hunter** [comment]
@nvborisenko i've created PR that fixes this problem for xUnit. But I have not tested it with another frameworks. The result looks like this
![image](https://user-images.githubusercontent.com/3284574/62276334-7c73f880-b44c-11e9-9ab5-35b48693b9eb.png)

**Comment by nvborisenko** [comment]
This works for xunit, but doesn't work for nunit. You can play with `example-net-vstest` repository to verify your package.

**Comment by yurii-hunter** [comment]
@nvborisenko will do. Thanks for a feedback
