### ISSUE TITLE
xunit theory decorators can cause tests not to be reported

### ISSUE THREAD

**Issue by ghost** [reportportal/agent-net-vstest#29]
xunit tests with inline data containing '.' will break this code
```  
private void Events_TestResult(object sender, TestResultEventArgs e)
        {
            var fullName = e.Result.TestCase.FullyQualifiedName;
            var testName = e.Result.TestCase.DisplayName?.Split('.').Last() ?? fullName.Split('.').Last();
```
example test decorator
[Theory]
[InlineData(@"<root><testValue>123</testValue></root>", foobar.yes)]
[InlineData(@"<root><testValue>NotADate</testValue></root>", foobar.no)]
[InlineData(@"<root><testValue>1.1</testValue></root>", foobar.yes)]
[InlineData(@"<root><testValue>NotANumber</testValue></root>", foobar.no)]

**Comment by nvborisenko** [comment]
@mhunting did you resolve the issue? How?

**Comment by ghost** [comment]
Yes, I did resolve the issue, but I modified the logger logic in test
result method, here's my commit link on my repo
https://github.com/mhunting/agent-net-vstest/commit/21fa44b8690d8a1edff4f70713b2988a9616f288.
I haven't had much time to test the change but it seems to be working.
