### ISSUE TITLE
Schema URL from Readme returns a 404

### ISSUE THREAD

**Issue by navisayslisten** [reportportal/agent-net-vstest#33]
The URL used in the Readme's config example: 
https://raw.githubusercontent.com/reportportal/agent-net-vstest/master/ReportPortal.VSTest.TestLogger/ReportPortal.config.schema 
does not exist. Depending on your IDE, the config file that includes this URL will cause a JSON schema error.

You probably meant to include the src folder. The URL that works is
https://raw.githubusercontent.com/reportportal/agent-net-vstest/master/src/ReportPortal.VSTest.TestLogger/ReportPortal.config.schema

**Comment by nvborisenko** [comment]
Fixed, thx.
