### ISSUE TITLE
Data driven tests displayed without data used for test

### ISSUE THREAD

**Issue by suszi88** [reportportal/agent-net-vstest#34]
Versions:
![image](https://user-images.githubusercontent.com/54896782/64542392-66930680-d31b-11e9-8988-4b22fc633b92.png)
When running Data driven tests, ReportPortal display them without information of data used for tests, so it's hard to distinguish which test case failed. Please see images bellow: 
Data driven test:
![image](https://user-images.githubusercontent.com/54896782/64542626-cdb0bb00-d31b-11e9-8428-570697c7fe7f.png)
Test result:
![image](https://user-images.githubusercontent.com/54896782/64542652-db664080-d31b-11e9-8b26-c17520a0b3fc.png)
ReportPortal:
![image](https://user-images.githubusercontent.com/54896782/64542728-fe90f000-d31b-11e9-9f1e-306a40c056f3.png)

**Comment by nvborisenko** [comment]
Moreover in report we see 4 tests, but actually should see 3 tests.

**Comment by nvborisenko** [comment]
@suszi88, fixed in v2.3.0, please verify.

**Comment by suszi88** [comment]
Tested with version: 2.3.0
Result: passed
Test case:
![image](https://user-images.githubusercontent.com/54896782/64784588-591b8d80-d562-11e9-82c5-e4b2f7dfd2fc.png)
ReportPortal:
![image](https://user-images.githubusercontent.com/54896782/64784711-9ed85600-d562-11e9-9f7e-3bef57796d5d.png)
