### ISSUE TITLE
How to get testItem id (vstest, c#)

### ISSUE THREAD

**Issue by heilwood** [reportportal/agent-net-vstest#35]
How to find current testItemId, i'm using ReportPortal VStest logger to send items to reportportal, i found example with NUnit.

            private void ReportPortalListener_AfterTestStarted(object sender, TestItemStartedEventArgs e)
            {
                e.TestReporter.Log(new ReportPortal.Client.Requests.AddLogItemRequest
                {
                    Level = ReportPortal.Client.Models.LogLevel.Trace,
                    Time = DateTime.UtcNow,
                    Text = "This message is from 'ReportPortalListener_AfterTestStarted' event."
                });
            }

            Bridge.Service.AddLogItemAsync(new AddLogItemRequest
            {
                TestItemId = e.TestReporter.TestId,
                Text = "Screenshot",
                Time = DateTime.UtcNow,
                Attach = new Attach("Image", "image/jpeg", imgdata),
                Level = LogLevel.Info
            });

Cannot figure out how to add attachment to the test. (Test adapter specrun)

Thank you!

**Comment by nvborisenko** [comment]
Fixed in v2.3.1

**Comment by heilwood** [comment]
working fine, thank you so much !!
