### ISSUE TITLE
How to attach screenshots

### ISSUE THREAD

**Issue by BilalKhan199** [reportportal/agent-net-vstest#36]
Hi,

I'm unable to find an example to attach screeshots in the test, can you please share an example?

Thanks in advance,
Bilal

**Comment by nvborisenko** [comment]
https://github.com/reportportal/example-net-vstest/blob/master/ExampleUnitTests/MsTests/MsTestClass1.cs#L42

Or
```csharp
ReporPortal.Shared.Log.Info(...);
```

**Comment by BilalKhan199** [comment]
> https://github.com/reportportal/example-net-vstest/blob/master/ExampleUnitTests/MsTests/MsTestClass1.cs#L42
> 
> Or
> 
> ```cs
> ReporPortal.Shared.Log.Info(...);
> ```

Thank you! it works
