### ISSUE TITLE
Tags show as values not keys 

### ISSUE THREAD

**Issue by rshelby5** [reportportal/agent-net-vstest#38]
Tried using latest version 3.0.0-beta.2 and 2.3.9 and when using tags in the config.json the UI shows tags as values not keys.

![Capture](https://user-images.githubusercontent.com/5266581/76614388-f8a7e180-64ed-11ea-8cb0-2b60ae33668b.PNG)

**Comment by DzmitryHumianiuk** [comment]
It works as designed.
Tags (from v4) will be stored as Value of attribute.

@nvborisenko should I close it?

**Comment by nvborisenko** [comment]
No, we want to use `attributes` instead of `tags`. We are in progress of deprecating `tags` on all agents.

**Comment by nvborisenko** [comment]
Reopening until it will be released.

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko does it make sense to keep issue open until released?

I guess the idea which GH pushes, like once one fixed issue -> ticket closed -> assigned to particular milestone -> await for milestone release
