### ISSUE TITLE
Append tags to via cli switch or environment variable

### ISSUE THREAD

**Issue by jrsearles** [reportportal/agent-net-vstest#40]
Currently you can set the tags via a CLI switch, however it would be nice if you could append some additional metadata to the tags already set instead of replacing them. This would allow us to easily append build information in CI builds while preserve existing static tags.

**Comment by nvborisenko** [comment]
If configuration value starts with `++` it should be appended.

We need document it.

**Comment by jrsearles** [comment]
Thank you! I've confirmed that this works. You can close this, unless you'd like to keep it open as a reminder to document this functionality.
