### ISSUE TITLE
[v5]Unable to pass multiple Report Portal attributes through VSTest command line arguments

### ISSUE THREAD

**Issue by sindyinturi** [reportportal/agent-net-vstest#42]
**Describe the bug**
I am trying to pass multiple report portal attributes using VStest command line arguments.

/Logger:trx /Logger:ReportPortal;launch.name="Launch_Name";launch.attributes="a":"a","b":"b";launch.description="description"

**To Reproduce**

**Expected behavior**
Although i am passing  key value pairs , in RP i can see the key as "a" and Value as "a,b:b"

How do I pass multiple arguments

**Comment by nvborisenko** [comment]
Please try `launch.attributes="a:a;b:b"`

**Comment by sindyinturi** [comment]
@nvborisenko As the standard delimiter between multiple Report portal 'launch' properties is ; (semi-colon) , your approach did not work

**Comment by nvborisenko** [comment]
My apologies, `,` is expected as delimiter of attributes key/value pairs.

Checked on `beta.6` - doesn't work as expected.

https://github.com/reportportal/agent-net-vstest/blob/6aad56312f78fa454e9e30eab18c239f712a494f/src/ReportPortal.VSTest.TestLogger/Configuration/LoggerConfigurationProvider.cs#L27

**Comment by nvborisenko** [comment]
Fixed. Will be available in `v3.0.0`. As a workaround you can use another approach to provide launch attributes: https://github.com/reportportal/commons-net/blob/develop/docs/Configuration.md#configuration-source

**Comment by sindyinturi** [comment]
@nvborisenko Thank you for all your help!
