### ISSUE TITLE
Could not find a test logger with URI or FriendlyName 'ReportPortal'

### ISSUE THREAD

**Issue by shilpa25comp** [reportportal/agent-net-vstest#46]
Getting error "Could not find a test logger with URI or FriendlyName 'ReportPortal'." with vstest.console.exe and logger ReportPortal.
[Diag.txt](https://github.com/reportportal/agent-net-vstest/files/5095800/Diag.txt)
Attached is Diag.txt
Also all RP dlls, test dll and RP.config.json are in same folder

This is working on my local machine where VS professional is installed vstest.console version 16.4.0
Fails on agent machine where vstest.console version is 15.7 and 16.7.
Please help me understand and resolve the issue.

**Comment by nvborisenko** [comment]
Based on diagnostic messages I see RP versions mismatching. Your versions:
```
ReportPortal.VSTest.TestLogger, Version=3.0.1.0
ReportPortal.Shared, Version=2.5.0.0
ReportPortal.Client, Version=2.1.15.0
```

But `ReportPortal.VSTest.TestLogger v3.0.1` requires `ReportPortal.Shared v3.0.0`. How did you install agent, as nuget package? If yes, versions should be resolved automatically.

**Comment by shilpa25comp** [comment]
You are right. I have added "ReportPortal.Shared" and "ReportPortal.Client" through nuget.
In my solution, I have added latest versions(3.0) in my project.
However, I have another project in my solution, which is used by some other team and they have added old reference versions(2.5).
After building solution, old version dlls are getting copied in agent machine execution directory.
Is it possible to have both versions dll in execution directory?

**Comment by nvborisenko** [comment]
No at now, and no in future :)

**Comment by nvborisenko** [comment]
@shilpa25comp do you want to say that old reference is copied to unexpected location?

Let's say you have ProjectA (which uses old version) and ProjectB (with the latest version)
```
ProjectA/bin/Debug
ProjectB/bin/Debug
```

And `ProjectB/bin/Debug` contains old version?

**Comment by shilpa25comp** [comment]
No, the references were being copied as expected in respective bin folders.
We contacted other team and got their references upgraded.
Thank you for your quick responses. It helped me identify the issue.
