### ISSUE TITLE
Integration with Serilog sink

### ISSUE THREAD

**Issue by mide1234** [reportportal/agent-net-vstest#47]
Hi,

I have a question. When using `agent-net-vstes` together with` logger-net-serilog` - why do I still need to specify the logger for `dotnet test -l:ReportPortal` command. One would think that enabling the Report Portal sink (see bellow) could be enough.

```
Log.Logger = new LoggerConfiguration().WriteTo.ReportPortal().CreateLogger();
```
So to put it in another words. I would assume that the code above is enough and running just `dotnet test` without any logger parameter should report the results to the Report Portal instance.

Thanks for clarification.

**Comment by nvborisenko** [comment]
`dotnet test -l:ReportPortal` says you want report test results, `Log.Logger = new LoggerConfiguration().WriteTo.ReportPortal().CreateLogger();` says you want report log messages from serilog as well.

**Comment by mide1234** [comment]
Right, that makes sense to me. Thanks for clarification.
