### ISSUE TITLE
Incorrect data driver test execution time logging for mstest

### ISSUE THREAD

**Issue by Shakevg** [reportportal/agent-net-vstest#49]
Execute data driver mstest using vstest.console.exe (locally or in AzuredevOps)
=> Execution time for all data driver tests is the same (equal sum of all data driver tests execution related to one auto-test).
See screenshot and *.trx file
![image](https://user-images.githubusercontent.com/42133199/96175834-1df14800-0f34-11eb-8676-483f8ce251d3.png)
[VssAdministrator_WIN-RNHA01V13BF_2020-10-13_08_26_08.zip](https://github.com/reportportal/agent-net-vstest/files/5387277/VssAdministrator_WIN-RNHA01V13BF_2020-10-13_08_26_08.zip)

**Comment by nvborisenko** [comment]
Reproduced for DDT.
