### ISSUE TITLE
Log4net/Nlog logs are not transferred to the Report Portal

### ISSUE THREAD

**Issue by UladzislauHlebau** [reportportal/agent-net-vstest#5]
Log4net/Nlog logs are not transferred to the Report Portal if to use VSTEST.

**Comment by nvborisenko** [comment]
2 blockers here:
1. vstest doesn't provide information that test starts for execution. So nlog doesn't know for which test the log message belongs to
2. https://github.com/reportportal/commons-net/issues/5
