### ISSUE TITLE
[FEATURE] Support report skip tests without defect type via configuration

### ISSUE THREAD

**Issue by Shakevg** [reportportal/agent-net-vstest#51]
By default, skip tests mark with To_Investigate defect type and need to analyze it every time.

We can handle it via rp.skipped.issue = option to mark skipped tests as not 'To Investigate' items on Server side. Boolean values: TRUE - skipped tests considered as issues and will be marked as 'To Investigate'. FALSE - skipped tests will not be mark as 'To Investigate' on the portal.
https://stackoverflow.com/a/40787123/8951897

Please add support of configuration this flag like Java Client https://jitpack.io/p/reportportal/client-java

**Comment by DzmitryHumianiuk** [comment]
Please see implementation in `client-java`

In few words: you should send issue `type` with name `NOT_ISSUE` in case if you don't need `To Investigate` flag for skipped/any testItem.
https://github.com/reportportal/client-java/commit/36c1624da17694fc2355ab0f628b2f1cc8a35c96#diff-69c3ef7f422402a9c55c68c001df11d1a06d0bd0c1df2d4e2e59406b50c91e2bR317

https://github.com/reportportal/client-java/commit/36c1624da17694fc2355ab0f628b2f1cc8a35c96

**Comment by nvborisenko** [comment]
Open questions to discuss:
- user investigates skipped tests manually, and then auto-analyzer helps
- should this behavior be configurable? or skipped tests are not needed for investigation by default (my opinion)

Please vote

**Comment by Shakevg** [comment]
@nvborisenko I vote for "skipped tests are not needed for investigation by default (my opinion)" for this flag because for me it is expected behavior.
But maybe the ability to specify such flags from the configuration will be useful for other flags like here https://github.com/reportportal/client-java#jvm-based-clients-configuration that not configurable now for agent-net-vstest.
