### ISSUE TITLE
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'ReportPortal'.

### ISSUE THREAD

**Issue by nickkildibekov** [reportportal/agent-net-vstest#56]
Hi, could you please help with the next question:
At the moment, I ran into problems with the implementation of the **_ReportPortal + VSTest_** integration.
When trying to run tests locally VIA Test Explorer and get a report, I get the error **Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'ReportPortal'.**
Everything is configured according to the documentation, there is no reason not to work.
Tell me please what is wrong.
I am using _**ReportPortal.VSTest.TestLogge**_r Version="[2.3.9]" and at the moment cannot update it for a lot of reasons
I can provide code without secur info, of course)
Test.runsettings
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <TestAdaptersPaths>.</TestAdaptersPaths>
    <MaxCpuCount>4</MaxCpuCount>
  </RunConfiguration>
  <TestRunParameters>
    <Parameter name="machineName" value="" />
  </TestRunParameters>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="ReportPortal">
        <Configuration>
          <Launch.Description>Ran from Visual Studio Test Explorer</Launch.Description>
        </Configuration>
      </Logger>
    </Loggers>
  </LoggerRunSettings>
</RunSettings>
```
 
ReportPortal.config.json
```
{
  "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-vstest/master/src/ReportPortal.VSTest.TestLogger/ReportPortal.config.schema",
  "enabled": true,
  "server": {
    "url": "<corporate-report-portal-app-url>",
    "project": <project-name>",
    "authentication": {
      "uuid": "<private-uuid>"
    }
  },
  "launch": {
    "name": "<launch-name>",
    "description": "this is description",
    "debugMode": false,
    "attributes": [ "t1", "os:win10" ]
  }
}
```

**Comment by Shakevg** [comment]
@nickkildibekov
What is the .Net target are you using for the project, what is a version of Visual Studio?
Is it working from the command line or without runsettings file?

**Comment by nvborisenko** [comment]
Related conversation in slack https://reportportal.slack.com/archives/C2GTJTTNH/p1622650034124600?thread_ts=1622650034.124600&cid=C2GTJTTNH

**Comment by nvborisenko** [comment]
Closing it, covered by https://github.com/reportportal/agent-net-vstest/issues/27
