### ISSUE TITLE
[FEATURE] Add rerun tests from Azure DevOps Visual Studio Test with retry logic to RP

### ISSUE THREAD

**Issue by Shakevg** [reportportal/agent-net-vstest#57]
[Azure DevOps Visual Studio Test](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops) support re-run failed tests, but RP creates a new launch for each rerun. 
It will be great to add rerun tests as retry in RP.

**Comment by nvborisenko** [comment]
Finally it's implemented as an extension for all agents - https://github.com/nvborisenko/reportportal-extensions-ci

Why not here:
- agent knows nothing about Azure (or any other CI)
- even if it will come here then others agents will want this feature

The extension above understands whether launch is rerun or not and modifies execution on fly.

**Comment by nvborisenko** [comment]
Closing it due it's managed by external extension.
