### ISSUE TITLE
Customize configurations parameters for ReportPortal.conf from agent-net-vstest

### ISSUE THREAD

**Issue by ValeriiFedorenko** [reportportal/agent-net-vstest#6]
As a user, I want for each build Configuration in team city customize parameters for reportPortal.cong like "launch name". 
Example:
```dotnet vstest bin/Debug/netcoreapp2.1/publish/Tests.dll --filter "TestCategory=Smoke" --logger:ReportPortal; LaunchName=Smoke```

**Comment by nvborisenko** [comment]
Implemented in v1.0.6
