### ISSUE TITLE
Merge launches

### ISSUE THREAD

**Issue by heilwood** [reportportal/agent-net-vstest#60]
Hi,

Is it possible to merge two different launches which is running in parallel? Found for specflow agent and nunit, but is it possible to merge using vstest agent?

**Comment by nvborisenko** [comment]
The same approach https://github.com/reportportal/commons-net/blob/master/docs/Configuration.md#reporting-experience

**Comment by heilwood** [comment]
Can you explain please how to use regular files or env. variables. For example where i should keep ReportPortal_Launch_Id.txt with value? Currently i'm creating the launch using reportportal api and powershell script from azureDevops pipeline step in another step i writing this launch id to file and saving to bin/Debug and nothing happens, still separate launches

**Comment by nvborisenko** [comment]
You are doing right, but file name should be ReportPortal_Launch_Id, without .txt extension.

**Comment by heilwood** [comment]
Looks like i'm doing something wrong: Attached screenshots of my configuration. File created, id added to file, but launches still running in parallel.

![startLaunch](https://user-images.githubusercontent.com/27227165/132495753-b27ca094-344b-4dc7-8621-e77e3210c850.png)
![saveLaunchIdToFile](https://user-images.githubusercontent.com/27227165/132495746-2f0a97aa-fc5d-4812-b1a4-7e900c0a9f26.png)
![savedFileWithLaunch](https://user-images.githubusercontent.com/27227165/132495750-b4e4944b-b4c8-4632-871c-1cc22ffe221b.png)
![launches_in_reportportal](https://user-images.githubusercontent.com/27227165/132495752-0faf7f4a-d0ff-4cc7-aa92-83bbef82cbd0.png)

**Comment by nvborisenko** [comment]
You put launch `number` instead of `uuid`. UUID is GUID type.

![image](https://user-images.githubusercontent.com/22616990/132511183-3e24e4a4-8c37-47da-8379-31e725350269.png)

If it doesn't work please share your agent`s version.

**Comment by heilwood** [comment]
Switched to UUID, same issue. Also in my project i have ReportPortal.config.json, maybe here is conflict?

![image](https://user-images.githubusercontent.com/27227165/132513039-ef43ab7e-4f49-4e7d-be9e-7bde036f126b.png)
![image](https://user-images.githubusercontent.com/27227165/132513160-df4bb103-fdc8-4e37-a1af-0bb9ce90e04b.png)

**Comment by nvborisenko** [comment]
Reproduced it. The issue that the agent doesn't read your file at all.

https://github.com/reportportal/agent-net-vstest/blob/3644d3f530c4d5e2e8f226e262010f0e51f45454/src/ReportPortal.VSTest.TestLogger/ReportPortalLogger.cs#L49

Definitely should be fixed.

**Comment by heilwood** [comment]
> Reproduced it. The issue that the agent doesn't read your file at all.
> 
> https://github.com/reportportal/agent-net-vstest/blob/3644d3f530c4d5e2e8f226e262010f0e51f45454/src/ReportPortal.VSTest.TestLogger/ReportPortalLogger.cs#L49
> 
> Definitely should be fixed.

Didn't get it.. Should i update vstet testLogger nuget package to get this fix?

**Comment by nvborisenko** [comment]
Fixed in v3.1.1 please verify.

**Comment by heilwood** [comment]
thank you very much, bug has been fixed
