### ISSUE TITLE
Not able to attach screenshot with report portal when upgrading ReportPortal.VSTest.Logger version from 1.2.3 to 2.0 or greater

### ISSUE THREAD

**Issue by zeeshankhan0330** [reportportal/agent-net-vstest#62]
![image](https://user-images.githubusercontent.com/18713129/150347681-6d988fdf-036e-43ed-b0fa-56c34b0b4842.png)

![image](https://user-images.githubusercontent.com/18713129/150347787-7488237e-fe04-4967-910b-adabfee91b13.png)

**Comment by nvborisenko** [comment]
@zeeshankhan0330 please provide simple test project to reproduce the issue.

**Comment by zeeshankhan0330** [comment]
@nvborisenko  - please find sample project here - https://github.com/zeeshankhan0330/RpScreenshotIssue

**Comment by nvborisenko** [comment]
SpecRun, SpecFlow, MsTest, RP agents for SpecFlow and VsTest at the same time. What is your toolset? In your provided sample I just deleted `ReportPortal.VsTest.TestLogger` package and screenshot came to RP.

Why not to use the latest versions? In any case fix will be included in the latest version only.

**Comment by zeeshankhan0330** [comment]
@nvborisenko  Removing ReportPortal.VsTest.TestLogger did solve the issue.
But now I am getting below error on running my tests through command line

![image](https://user-images.githubusercontent.com/18713129/150502929-579e9cf9-84a4-4a85-9cb6-485b98d7d049.png)

**Comment by zeeshankhan0330** [comment]
We are planning to move to latest version but it will take some time. before that it would be great if u could help us with this

**Comment by zeeshankhan0330** [comment]
I have tried upgrading Specrun, Reportportal shared, Specflow Report portal but logger issue seem to not resolved.

It is only getting resolved by adding Vstest logger but that inroduces screenshot issue

**Comment by zeeshankhan0330** [comment]
Reason for upgrading vstest logger from 1.2.3 to 2.x was that launch name was not getting passed through cmd. We managed to solve this problem by passing the launch name via env variable setting.
