### ISSUE TITLE
Please extend configuration set-up from CLI

### ISSUE THREAD

**Issue by r2oster** [reportportal/agent-net-vstest#9]
The `ReportPortal.config.json` contains a variety of important parameters that the users would like to set up from CI before launches, rather than update inside the file.
In addition to `Launch.Name="<value>"`, please extend the semicolon separated configuration settings list via a command line as follows:

1. Highest priority: 
 * `Launch.Tags="<Tag1>[;<Tag2>[;...]]"`
 * `Launch.DebugMode=(true|false)`

2. Medium priority:
 * `Launch.Description="<value>"`

3. Lower priority:
 * `Project="<value>"`
 * `Authentication.Uuid="<value>"`

**Comment by nvborisenko** [comment]
Available in v1.2.2
